[project]
name = "pytool"
version = "0.1.217"
description = "A tool for MD simulation"
readme = "README.md"
requires-python = ">=3.10"
authors = [{ name = "2lu3", email = "hi2lu3@gmail.com" }]
dependencies = [
    "mdanalysis>=2.8.0,<3.0.0",
    "click>=8.1.7,<9.0.0",
    "natsort>=8.4.0,<9.0.0",
    "loguru>=0.7.0,<0.8.0",
    "toml>=0.10.2,<0.11.0",
    "biopython>=1.81,<2.0.0",
    "jinja2>=3.1.2,<4.0.0",
    "requests>=2.32.3,<3.0.0",
    "matplotlib>=3.10.0,<4.0.0",
    "japanize-matplotlib>=1.1.3,<2.0.0",
    "alive-progress>=3.2.0,<4.0.0",
]

[project.scripts]
create-repository = "pytool.command.repository:to_command"
set-chain-id = "pytool.chain.set_chain_id:set_chain_id_to_command"
increment-dir = "pytool.directory.increment_directory_index:increment_directory_index_to_command"
copy-template = "pytool.directory.copy_template:copy_template_to_command"
analyze-production = "pytool.log_analyzer.production:command"
analyze-equilibration = "pytool.log_analyzer.equilibration:command"
analyze-equilibrations = "pytool.log_analyzer.equilibrations:command"
analyze-minimization = "pytool.log_analyzer.minimization:command"
analyze-minimizations = "pytool.log_analyzer.minimizations:command"
plot-2d = "pytool.plot.plot_2d:plot_2d_to_command"
pickup-aligned-seq = "pytool.sequence.pickup_aligned_sequence:main"
rename2charmm = "pytool.sequence.rename2charmm:main"
residue-distance = "pytool.structure.residue_distance:residue_distance_to_command"
atom-distance = "pytool.structure.atom_distance:atom_distance_to_command"
rmsd = "pytool.structure.rmsd:rmsd_to_command"
rmsd-trajectory = "pytool.structure.rmsd:rmsd_trajectory_to_command"
get-boxsize = "pytool.structure.get_box_size:get_box_size_to_command"
concat-dcd = "pytool.trajectory.__init__:concat_dcd"
sample-trajectory = "pytool.trajectory.sample_trajectory:command"
reduce-dcd = "pytool.trajectory.reduce_dcd:reduce_dcd_to_command"
dcd-moving-average = "pytool.trajectory.moving_average:moving_average_to_command"
dvc-add = "pytool.useful_commands.dvc:dvc_add_to_command"
install-genesis = "pytool.useful_commands.genesis:install_genesis_to_command"
install_genesis_requirements = "pytool.useful_commands.genesis:install_genesis_requirements_to_command"

[dependency-groups]
dev = [
    "black>=23.7.0,<24.0.0",
    "pytest>=7.4.0,<8.0.0",
]

[build-system]
requires = ["hatchling>=1.26.0"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["pytool"]
